### ISSUE TITLE
Order has status "new" and primary shop owner can nothing to do with it

### ISSUE THREAD

**Issue by OlehObodin** [reactioncommerce/api-plugin-orders#55]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact us instead. We are active in gitter and twitter:
[](https://user-images.githubusercontent.com/100937342/163420146-fc4752da-a321-4037-9542-518764bc8720.png)[](https://user-images.githubusercontent.com/100937342/163420499-d812484c-24ca-4340-bc1b-f073dfeb3fba.png)Issue Description

Then I got the new order to the shop admin with testing stripe credentials I can't process the order even I approve It inside stripe account
Steps to Reproduce

Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1.Get new payed order with testing credentials
2. Approve order inside stripe dashboard
3.Go to the orders and order has still new status and nothing can do with it

Possible Solution
![image](https://user-images.githubusercontent.com/100937342/163422795-61d2f4c1-829c-42d9-a27a-26da94fb066d.png)
![image](https://user-images.githubusercontent.com/100937342/163422844-4dd8e0ec-1250-499b-90b4-0bb9bb8bc7c6.png)

Not obligatory, but suggest a fix/reason for the bug

**Comment by brent-hoover** [comment]
This is a limitation of the existing admin, not of the orders plugin. There is no bug here, closing.
